### ISSUE TITLE
Change file-based input to Reader for increased flexibility

### ISSUE THREAD

**Issue by rjyounes** [ld4l-labs/bib2lod#10]
Conversion data doesn't have to reside on a file system but can be streamed to the converter.

**Comment by zimeon** [comment]
I have been thinking that for testing it would be nice to have a way to run the converter on a single record with input via stdin, output via stdout, ie.

```
cat record.marc | java -jar converter.jar > output.rdf
```

I was thinking of making a modified version of `SimpleManager` but perhaps there are better ways.

**Comment by rjyounes** [comment]
Yes, I like this idea. 

Notes more or less to myself: Configuration should store a list of Readers rather than a  list of files or paths. This can't be done in the manager because the Configuration interface needs to specify a constant return type. The config file specifies the input or perhaps nothing to read from stdin. For now, change Configuration to work with Readers instead of files; accommodate input from stdin and output to stdout later.
