### ISSUE TITLE
Connect Instance and Work

### ISSUE THREAD

**Issue by zimeon** [ld4l-labs/bib2lod#37]
It seems that the current output for the [minimal record](https://github.com/ld4l-labs/bib2lod/blob/develop/sample-data/marcxml-to-ld4l/cornell/102063-min/102063.min.ttl) has both a Work and an Instance but they are not connected. I assume there should be a bf:instanceOf or bf:hasInstance triple.

**Comment by rjyounes** [comment]
The output from the application does contain instanceOf triples. Are you referring to the sample output 102063.min.ttl?

**Comment by rjyounes** [comment]
Live output and sample output on both develop and master now include a bf:instanceOf relation between instance and work.

**Comment by zimeon** [comment]
commit: 69e47942a00c1a86ffb3bdfb9bd222fb67953b57
