### ISSUE TITLE
Functional tests not working

### ISSUE THREAD

**Issue by rjyounes** [ld4l-labs/bib2lod#40]
Second test fails:

   def test02_cornell_ld4l_conversion(self):
        """Test Cornel LD4L conversions based on sample configuration file."""
        indirs = 'sample-data/marcxml-to-ld4l/cornell'
        outdir = self.tmpdir
        for indir in glob.glob(os.path.join(indirs, '*')):
            # FIXME - should look for *.xml in each dir and then build tests on that
            src = os.path.join(indir, '102063.min.xml')
            ref = os.path.join(indir, '102063.min.ttl')
            dst = os.path.join(outdir, '102063.min.ttl')
            config = example_config()
            config['InputService']['source'] = src
            config['OutputService']['destination'] = outdir
            config_filepath = self.write_config(config)
            out = run_bib2lod([config_filepath])
            self.assertTrue(os.path.exists(dst))
>           self.assertEqual(RDiffB(['data.ld4l.org/cornell']).compare_files([ref, dst]), 0)
E           AssertionError: 20 != 0

tests_functional/test_bib2lod.py:64: AssertionError

Note that I modified the code in my directory to expect turtle output, since I found input/output comparisons easier. Change output format in the config to TURTLE.

I've examined the input and output and can't find any differences.

**Comment by rjyounes** [comment]
I've temporarily disabled the functional tests so we get a passing grade on travis, until we can fix them.

**Comment by zimeon** [comment]
@rjyounes - seems that you might have identified a problem with the diff, please will you make gists of the two ttl files that should show a match and link from the ticket, then I'll know I'm working with the right things

**Comment by rjyounes** [comment]
See expected and actual output: https://gist.github.com/rjyounes/f7819164fc4dcbb256663edcac128706

**Comment by zimeon** [comment]
Sanity check: No diff shown between the `nt` and `ttl` versions of actual output from [gist](https://gist.github.com/rjyounes/f7819164fc4dcbb256663edcac128706):

```
(py3)simeon@RottenApple gist> rdfdiffb.py -s -b http://data.ld4l.org/cornell/ 102063.min.actual.nt 102063.min.actual.ttl 
Graphs 102063.min.actual.nt and 102063.min.actual.ttl are isomorphic after bnode substitutions
```

Real test: It turns out that the difference between the actual and expected outputs is a difference in the `bf:responsibilityStatement` literal. If I correct the single space after first sentence in `102063.min.expected.ttl` to be a double space, then the graphs match:

```
(py3)simeon@RottenApple gist> cat 102063.min.expected.ttl | perl -pe 's/Physicians. Editorial/Physicians.  Editorial/' > expected.fixed.ttl
(py3)simeon@RottenApple gist> rdfdiffb.py -s -b http://data.ld4l.org/cornell/ 102063.min.actual.nt expected.fixed.ttl 
Graphs 102063.min.actual.nt and expected.fixed.ttl are isomorphic after bnode substitutions
```

**Comment by rjyounes** [comment]
Expected output fixed and functional test restored to travis
